Parkj12b/issue3
seongil99/pingpong pull request #15
Opened 2024-11-13 15:22 UTC by parkj12b

다음 할 일:
-  recovery method 정하기
- admin 에서 리셋가능한지 체크

2024-11-13 15:26 UTC, parkj12b commented
TOTP secret 직접 보여주는것도 필요함

2024-11-14 07:35 UTC, seongil99 requested changes

2024-11-14 07:35 UTC, seongil99 commented on backend/docker-entrypoint.sh
> +python manage.py runserver 0.0.0.0:8000
docker-entrypoint.develop.sh로 분리하는 것이 좋아보입니다.

2024-11-14 07:35 UTC, seongil99 commented on backend/accounts/two_factor_auth/views.py
> +User = get_user_model()
from django.contrib.auth.models import User랑 중복되는데 전역으로 다시 선언하신 이유가 있나요?

2024-11-14 07:35 UTC, seongil99 commented on backend/accounts/two_factor_auth/views.py
> +from django.shortcuts import redirect
사용하지 않는 import는 특별한 이유가 없다면 제거하는 것이 좋아 보입니다.

2024-11-14 07:49 UTC, parkj12b commented on backend/accounts/two_factor_auth/views.py
> +User = get_user_model()
지금 보통 유저로 설정이 안되있더라구요 User 설정이 바뀌면 import 를 바꿔야되서 그거보단 get_user_model 상요하는게 좋아보였습니다.

2024-11-14 08:21 UTC, seongil99 requested changes

2024-11-14 08:21 UTC, seongil99 commented on backend/accounts/two_factor_auth/views.py
>  import qrcode
import qrcode가 2개네요

2024-11-14 08:21 UTC, seongil99 commented on backend/accounts/two_factor_auth/views.py
>  from django.contrib.auth.models import User
밑에 User 사용중이면 요거는 지워도 되지 않나요?

2024-11-14 08:21 UTC, seongil99 commented on backend/accounts/oauth2/views.py
> +from django.http import HttpResponse
from django_otp.plugins.otp_totp.models import TOTPDevice
from django.shortcuts import redirect
from django.http import HttpResponse

사용되지 않는 import 같습니다.

2024-11-15 01:14 UTC, seongil99 approved these changes
LGTM

2024-11-15 08:33 UTC, merged