Parkj12b/issue18
seongil99/pingpong pull request #27
Opened 2024-11-16 14:39 UTC by parkj12b

- 친구 추가 요청, 친구 요청 수락, 친구 요청 삭제 
- 테스트 작성 완료

2024-11-17 05:58 UTC, seongil99 requested changes

2024-11-17 05:58 UTC, seongil99 commented on backend/friends/tests.py
> +# Create your tests here.
test.py랑 tests.py의 차이는 무엇인가요?

2024-11-17 05:58 UTC, seongil99 commented on backend/friends/serializer.py
> +        fields = ['id', 'user1', 'user2', 'requester', 'status', 'created_at']
장고가 파일 이름을 기본적으로 복수형으로 하다 보니 serializers.py가 낫지 않을까요?

2024-11-17 06:17 UTC, parkj12b commented on backend/friends/tests.py
> +# Create your tests here.
tests.py로 작성해야되는걸로 알고 있습니다. python manage.py test 돌리면 tests.py 를 자동생성하게 되었습니다.

2024-11-17 06:18 UTC, parkj12b commented on backend/friends/serializer.py
> +        fields = ['id', 'user1', 'user2', 'requester', 'status', 'created_at']
수정하겠습니다 👍

2024-11-19 02:51 UTC, seongil99 approved these changes
LGTM

2024-11-19 06:40 UTC, merged