친구 검색 #22
seongil99/pingpong pull request #30
Opened 2024-11-18 13:27 UTC by parkj12b

- django-filter dependency 추가
- pagination 적용
- feat 는 각 commit 에

2024-11-19 22:16 UTC, seongil99 commented
풀리퀘 이름은 "issue/22"보다는 "친구 검색"처럼 기능으로 하고 이슈는 링크를 하는 쪽이 이해하기 쉬운 것 같아요

2024-11-19 22:44 UTC, seongil99 requested changes

2024-11-19 22:44 UTC, seongil99 commented on backend/friends/tests/tests.py
> +from django.urls import reverse
`friends/test/test.py`와 `friends/test.py`가 중복되는데 
`friends/tests.py`를 삭제하는 게 좋아 보입니다.

2024-11-19 22:44 UTC, seongil99 commented on backend/.idea/.gitignore
.idea 삭제한 이유가 있을까요?

2024-11-19 22:44 UTC, seongil99 commented on backend/api/urls.py
> +    path("users/search/friendable", SearchFriendableView.as_view(), name="search-friendable"),
friends 하위에 urls.py 만들어서
```
friends/requests
friends/requests/:id
friends/friendable
```

이런 식으로 하는 건 어떨까요?

2024-11-20 07:13 UTC, parkj12b commented on backend/friends/tests/tests.py
> +from django.urls import reverse
확인하겠습니다 👍

2024-11-20 07:13 UTC, parkj12b commented on backend/.idea/.gitignore
.idea 가 ide 설정파일인걸로 알고 있어서  .gitignore 에 추가만 했습니다

2024-11-20 11:15 UTC, parkj12b commented
아니 checkout pull 안하면 다른 브랜치는 pull 이 안되는군요 XD conflict resolve 하겠습니다

2024-11-22 01:29 UTC, seongil99 requested changes

2024-11-22 01:29 UTC, seongil99 commented on backend/users/urls.py
> +        "search/friendable",
url이 `search/`는 `/`로 끝나고 `friendable`은 `/`없이 끝나는데 통일하는 게 필요해 보입니다.

2024-11-22 09:11 UTC, seongil99 approved these changes
LGTM

2024-11-22 10:19 UTC, merged