친구 제거 #21, 친구 차단 #20
seongil99/pingpong pull request #33
Opened 2024-11-21 07:30 UTC by parkj12b

close #21 
close #20

2024-11-21 07:31 UTC, parkj12b commented
브랜치 따서 structure 바꾸기엔 develop 에 적용되지 않은점이 너무 많아서 같이 진행했습니다

2024-11-21 07:33 UTC, parkj12b commented
엄 테스트 fail

2024-11-22 01:33 UTC, seongil99 requested changes

2024-11-22 01:33 UTC, seongil99 commented on backend/users/friends/urls.py
> +    path("friend-requests", FriendRequestView.as_view(), name="friend-request"),
통일성을 위해 `friends-requests/`로 `/`로 끝나게 수정하는 것이 좋아 보입니다.

2024-11-22 09:13 UTC, seongil99 approved these changes
LGTM

2024-11-22 10:15 UTC, merged