Parkj12b/issue19 친구 online / offline 추가
seongil99/pingpong pull request #34
Opened 2024-11-21 14:58 UTC by parkj12b

- user model is_online, last_seen 추가
- wss 적용한 online 측정 backend endpoint 및 frontend one-way heartbeat 로직 추가

2024-11-22 08:49 UTC, seongil99 requested changes

2024-11-22 08:49 UTC, seongil99 commented on backend/users/urls.py
> +    path("", include("users.friends.urls")),
여기를 `friends/`로 하고 friends.urls에서는 하위 url만 적는 것이 낫지 않을까요?

2024-11-22 09:12 UTC, parkj12b commented on backend/users/urls.py
> +    path("", include("users.friends.urls")),
friend-request 도 friends 안에 추가되어 있어서 그러면 friend-request 를 friends/friend-request 로 해야되서 /friend 리소스의 friend-request 인거처럼 느껴져서 따로 두었습니다.

2024-11-22 09:14 UTC, seongil99 commented on backend/users/urls.py
> +    path("", include("users.friends.urls")),
`friends/request/`나 `friends/requests/` 는 어떨까요?

2024-11-22 10:17 UTC, parkj12b commented on backend/users/urls.py
> +    path("", include("users.friends.urls")),
그게 낫겠네요 수정하겠습니다 👍

2024-11-25 08:13 UTC, seongil99 approved these changes
LGTM

2024-11-26 05:50 UTC, merged